### PR TITLE
Add UA- prefix for UA hints

### PR DESCRIPTION
**Pull request by yoavweiss**
Accompanying PR to https://github.com/WICG/ua-client-hints/pull/38

### CODE REVIEW

**Comment by amtunlimited** [comment]
LGTM

Should we also add the `UA` prefix to the client hint tokens in section 7.1? It feels a little weird (to me) that the header and hint token would be different

**Comment by yoavweiss** [comment]
> Should we also add the `UA` prefix to the client hint tokens in section 7.1? It feels a little weird (to me) that the header and hint token would be different

Isn't that what added in https://github.com/WICG/client-hints-infrastructure/pull/18/files#diff-ec9cfa5f3f35ec1f84feb2e59686c34dR306 ? Or are you talking about something else?

**Comment by amtunlimited** [comment]
No, you're right. I thought it was something else because in the [rendered version](https://wicg.github.io/client-hints-infrastructure/#client-hints-token-definition) there aren't any line breaks (which should probably get fixed)

**Comment by yoavweiss** [comment]
Thanks for reviewing! :)

**Pull request merged**
