### PR TITLE
Fixes #59 - Add a UA-Bitness hint

### LINKED ISSUE #59: Add "UA-bitness" hint in all the relevant spots
Which comes from https://github.com/WICG/ua-client-hints/issues/105 (and the linked PR).

### PR DESCRIPTION
**Pull request by miketaylr**
This is the infra half to https://github.com/WICG/ua-client-hints/pull/210

(And apparently we forgot to add UA-Platform-Version 🙈 )

### CODE REVIEW

**Comment by miketaylr** [comment]
PTAL, @yoavweiss

**Review by yoavweiss — APPROVED** [review]
LGTM once the other half lands :)

**Comment by miketaylr** [comment]
Thanks!

**Comment by bat999** [comment]
Hi
Anybody here from Google?
Please add a bitness test to this demo ---> https://user-agent-client-hints.glitch.me/

**Comment by miketaylr** [comment]
Hi @bat999. Thanks, good reminder. Once we're certain we want to implement it as specced, we can do that.

**Pull request merged**
